### ISSUE TITLE
The Logout generates a pug error

### ISSUE THREAD

**Issue by carbondigitalus** [carbondigitalus/carbonbuilderapp#2]

**Comment by carbondigitalus** [comment]
ERROR IN BROWSER: 

TypeError: /Applications/MAMP/htdocs/Carbon_Digital/Carbon_Builder/carbon-builder-private/views/app-dashboard/_header.pug:120
    118|       a(href='#' data-toggle='dropdown')
    119|         figure.profile-picture
  > 120|           img.rounded-circle(src=`img/users/${user.profileAvatar}` alt=`${user.firstName} ${user.lastName}` data-lock-picture=`img/users/${user.profileAvatar}`)
    121|         .profile-info(data-lock-name=`${user.firstName} ${user.lastName}` data-lock-email=`${user.email}`)
    122|           span.name= `${user.firstName} ${user.lastName}`
    123|           -if (user.appUserRole === 'employee-dev-front-end')

Cannot read property 'profileAvatar' of undefined
    at eval (eval at wrap (/Applications/MAMP/htdocs/Carbon_Digital/Carbon_Builder/carbon-builder-private/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:399:100)
    at template (eval at wrap (/Applications/MAMP/htdocs/Carbon_Digital/Carbon_Builder/carbon-builder-private/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2355:146)
    at Object.exports.renderFile (/Applications/MAMP/htdocs/Carbon_Digital/Carbon_Builder/carbon-builder-private/node_modules/pug/lib/index.js:427:38)
    at Object.exports.renderFile (/Applications/MAMP/htdocs/Carbon_Digital/Carbon_Builder/carbon-builder-private/node_modules/pug/lib/index.js:417:21)
    at View.exports.__express [as engine] (/Applications/MAMP/htdocs/Carbon_Digital/Carbon_Builder/carbon-builder-private/node_modules/pug/lib/index.js:464:11)
    at View.render (/Applications/MAMP/htdocs/Carbon_Digital/Carbon_Builder/carbon-builder-private/node_modules/express/lib/view.js:135:8)
    at tryRender (/Applications/MAMP/htdocs/Carbon_Digital/Carbon_Builder/carbon-builder-private/node_modules/express/lib/application.js:640:10)
    at Function.render (/Applications/MAMP/htdocs/Carbon_Digital/Carbon_Builder/carbon-builder-private/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/Applications/MAMP/htdocs/Carbon_Digital/Carbon_Builder/carbon-builder-private/node_modules/express/lib/response.js:1012:7)
    at /Applications/MAMP/htdocs/Carbon_Digital/Carbon_Builder/carbon-builder-private/controllers/viewController.js:47:19
    at /Applications/MAMP/htdocs/Carbon_Digital/Carbon_Builder/carbon-builder-private/utils/catchAsync.js:3:5
    at Layer.handle [as handle_request] (/Applications/MAMP/htdocs/Carbon_Digital/Carbon_Builder/carbon-builder-private/node_modules/express/lib/router/layer.js:95:5)
    at next (/Applications/MAMP/htdocs/Carbon_Digital/Carbon_Builder/carbon-builder-private/node_modules/express/lib/router/route.js:137:13)
    at exports.isLoggedIn (/Applications/MAMP/htdocs/Carbon_Digital/Carbon_Builder/carbon-builder-private/controllers/authController.js:167:14)
